name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r requirements-dev.txt
      - name: Lint
        run: |
          black --check src tests examples install.py
          flake8 src tests examples install.py
          mypy src
      - name: Run tests
        run: pytest --cov=src --cov-report=xml
      - name: Build Docker image
        run: docker build -t rfai-system .
